const reduxString = {
  REQUEST_ERROR: 'REQUEST_ERROR',
  SET_LIST_BIODATA: 'SET_LIST_BIODATA',
  REQUEST_LIST_BIODATA: 'REQUEST_LIST_BIODATA',
  RESET_LIST_BIODATA: 'RESET_LIST_BIODATA',
}

export default reduxString
